In [1]:
import numpy as np
import csv

In [2]:
path_csv = "训练位点和占据率/ch1训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch1_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(6557,)
(6557,)
[[1.         0.96072924]
 [0.96072924 1.        ]]


In [3]:
path_csv = "训练位点和占据率/ch2训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch2_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(29077,)
(29077,)
[[1.         0.95044651]
 [0.95044651 1.        ]]


In [4]:
path_csv = "训练位点和占据率/ch3训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch3_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(9140,)
(9140,)
[[1.         0.95755292]
 [0.95755292 1.        ]]


In [5]:
path_csv = "训练位点和占据率/ch4训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch4_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(54086,)
(54086,)
[[1.         0.96662106]
 [0.96662106 1.        ]]


In [6]:
path_csv = "训练位点和占据率/ch5训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch5_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(19920,)
(19920,)
[[1.        0.9619783]
 [0.9619783 1.       ]]


In [7]:
path_csv = "训练位点和占据率/ch6训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch6_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(8793,)
(8793,)
[[1.         0.95276176]
 [0.95276176 1.        ]]


In [8]:
path_csv = "训练位点和占据率/ch7训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch7_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(38445,)
(38445,)
[[1.         0.96735796]
 [0.96735796 1.        ]]


In [9]:
path_csv = "训练位点和占据率/ch8训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch8_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(19040,)
(19040,)
[[1.         0.96453555]
 [0.96453555 1.        ]]


In [10]:
path_csv = "训练位点和占据率/ch9训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch9_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(14270,)
(14270,)
[[1.         0.95229218]
 [0.95229218 1.        ]]


In [11]:
path_csv = "训练位点和占据率/ch10训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch10_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(25671,)
(25671,)
[[1.         0.29811444]
 [0.29811444 1.        ]]


In [12]:
path_csv = "训练位点和占据率/ch11训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch11_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(25094,)
(25094,)
[[1.         0.96528851]
 [0.96528851 1.        ]]


In [13]:
path_csv = "训练位点和占据率/ch12训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch12_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(36380,)
(36380,)
[[1.         0.96597612]
 [0.96597612 1.        ]]


In [14]:
path_csv = "训练位点和占据率/ch13训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch13_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(33587,)
(33587,)
[[1.         0.96765568]
 [0.96765568 1.        ]]


In [15]:
path_csv = "训练位点和占据率/ch14训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch14_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(27752,)
(27752,)
[[1.         0.96571786]
 [0.96571786 1.        ]]


In [16]:
path_csv = "训练位点和占据率/ch15训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch15_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(38604,)
(38604,)
[[1.         0.96533065]
 [0.96533065 1.        ]]


In [17]:
path_csv = "训练位点和占据率/ch16训练.csv" 
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[0,1]) 
ori = data[:,1]
print(ori.shape)
res = np.loadtxt('染色体预测结果（训练）/ch16_levelp(t).txt',dtype=np.float32)
print(res.shape)
cor = np.vstack([ori,res]) 
print(np.corrcoef(cor))

(34569,)
(34569,)
[[1.         0.96794162]
 [0.96794162 1.        ]]
