分割值: 2.439  2.711  2.656  2.682  2.659  2.522  2.753  2.574  2.6  2.712  2.623  2.93  2.703  2.715  2.709  2.62

分割值位点:  3166 13766 3249 27068 9180 3046 18894 9600 5080 12291 13356 17720 17706 14016 17859 20012

In [1]:
import numpy as np
import csv
import pandas as pd

In [2]:
path_csv = "分类染色体/ch1.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 

In [3]:
data.shape

(168234, 2)

In [4]:
data[0:5,1]

array([4.158, 4.142, 4.142, 4.127, 4.127])

In [5]:
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.439:
        num = num+1
print(num)

3167


In [6]:
high = data[0:3167][:]
print(high.shape)

(3167, 2)


In [7]:
mid = data[3167:168234][:]
print(mid.shape)

(165067, 2)


In [8]:
highx = np.zeros((int(3167/3), 2))
midx = np.zeros((int(165067/30), 2))
print(highx.shape)
print(midx.shape)

(1055, 2)
(5502, 2)


In [9]:
for h in range(int(3167/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)

[[1.68794e+05 4.15800e+00]
 [1.68797e+05 4.12700e+00]
 [1.68795e+05 4.12000e+00]
 ...
 [7.21660e+04 2.44000e+00]
 [4.32380e+04 2.43900e+00]
 [7.21620e+04 2.43900e+00]]


In [10]:
for m in range(int(165067/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

[[1.31037e+05 2.43800e+00]
 [4.40000e+04 2.43500e+00]
 [5.99560e+04 2.42700e+00]
 ...
 [1.99914e+05 1.55000e-02]
 [1.01289e+05 1.55000e-02]
 [1.76509e+05 1.55000e-02]]


In [11]:
Nuar = np.concatenate([highx, midx])
Nuar.shape

(6557, 2)

In [12]:
site = Nuar[:,0]
level = Nuar[:,1]
print(site.shape)
print(level.shape)

(6557,)
(6557,)


In [13]:
df = pd.DataFrame(Nuar,columns=['site','value'])

In [14]:
df.head()

site  value
0  168794.0  4.158
1  168797.0  4.127
2  168795.0  4.120
3  168791.0  4.118
4  168803.0  4.112

In [15]:
df.to_csv('训练位点和占据率/ch1训练.csv',index=False)

In [16]:
data = pd.read_csv('训练位点和占据率/ch1训练.csv')

In [17]:
data.head()

site  value
0  168794.0  4.158
1  168797.0  4.127
2  168795.0  4.120
3  168791.0  4.118
4  168803.0  4.112

In [18]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch2.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.711:
        num = num+1
print(num)

(748431, 2)
13767


In [19]:
high = data[0:13767][:]
print(high.shape)
mid = data[13767:748431][:]
print(mid.shape)

(13767, 2)
(734664, 2)


In [20]:
highx = np.zeros((int(13767/3), 2))
midx = np.zeros((int(734664/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(13767/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(734664/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(4589, 2)
(24488, 2)
[[5.34314e+05 4.52700e+00]
 [5.34315e+05 4.51900e+00]
 [5.34320e+05 4.51100e+00]
 ...
 [4.97459e+05 2.71100e+00]
 [1.41297e+05 2.71100e+00]
 [4.70354e+05 2.71100e+00]]
[[2.57538e+05 2.71000e+00]
 [7.33496e+05 2.71000e+00]
 [1.69789e+05 2.70900e+00]
 ...
 [5.63087e+05 1.55000e-02]
 [3.53632e+05 1.52000e-02]
 [3.53577e+05 1.52000e-02]]


In [21]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch2训练.csv',index=False)

(29077, 2)


In [22]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch3.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.656:
        num = num+1
print(num)

(244966, 2)
3250


In [23]:
high = data[0:3250][:]
print(high.shape)
mid = data[3250:244966][:]
print(mid.shape)

(3250, 2)
(241716, 2)


In [24]:
highx = np.zeros((int(3250/3), 2))
midx = np.zeros((int(241716/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(3250/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(241716/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(1083, 2)
(8057, 2)
[[4.71450e+04 4.18600e+00]
 [4.71440e+04 4.17900e+00]
 [4.71360e+04 4.17100e+00]
 ...
 [2.22007e+05 2.65800e+00]
 [4.90300e+04 2.65800e+00]
 [3.99510e+04 2.65800e+00]]
[[2.13550e+04 2.65500e+00]
 [2.47046e+05 2.65300e+00]
 [3.52830e+04 2.64800e+00]
 ...
 [2.60039e+05 1.55000e-02]
 [2.94600e+04 1.55000e-02]
 [2.92604e+05 1.55000e-02]]


In [25]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch3训练.csv',index=False)

(9140, 2)


In [26]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch4.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.682:
        num = num+1
print(num)

(1378420, 2)
27129


In [27]:
high = data[0:27129][:]
print(high.shape)
mid = data[27129:1378420][:]
print(mid.shape)

(27129, 2)
(1351291, 2)


In [28]:
highx = np.zeros((int(27129/3), 2))
midx = np.zeros((int(1351291/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(27129/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(1351291/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(9043, 2)
(45043, 2)
[[3.80350e+04 4.56500e+00]
 [3.80380e+04 4.56500e+00]
 [3.80330e+04 4.56500e+00]
 ...
 [3.34340e+05 2.68200e+00]
 [5.54208e+05 2.68200e+00]
 [3.18510e+05 2.68200e+00]]
[[1.286756e+06 2.681000e+00]
 [1.140185e+06 2.681000e+00]
 [1.494020e+06 2.680000e+00]
 ...
 [2.125190e+05 1.550000e-02]
 [1.095496e+06 1.520000e-02]
 [1.095512e+06 1.520000e-02]]


In [29]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch4训练.csv',index=False)

(54086, 2)


In [30]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch5.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.659:
        num = num+1
print(num)

(515003, 2)
9181


In [31]:
high = data[0:9181][:]
print(high.shape)
mid = data[9181:515003][:]
print(mid.shape)

(9181, 2)
(505822, 2)


In [32]:
highx = np.zeros((int(9181/3), 2))
midx = np.zeros((int(505822/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(9181/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(505822/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(3060, 2)
(16860, 2)
[[3.49700e+05 4.30600e+00]
 [3.49703e+05 4.25800e+00]
 [3.49708e+05 4.24900e+00]
 ...
 [2.88994e+05 2.65900e+00]
 [4.40286e+05 2.65900e+00]
 [4.08550e+04 2.65900e+00]]
[[4.40323e+05 2.65800e+00]
 [1.43633e+05 2.65800e+00]
 [3.34702e+05 2.65600e+00]
 ...
 [5.38382e+05 1.55000e-02]
 [5.20853e+05 1.55000e-02]
 [5.20845e+05 1.55000e-02]]


In [33]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch5训练.csv',index=False)

(19920, 2)


In [34]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch6.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.522:
        num = num+1
print(num)

(236402, 2)
3047


In [35]:
high = data[0:3047][:]
print(high.shape)
mid = data[3047:236402][:]
print(mid.shape)

(3047, 2)
(233355, 2)


In [36]:
highx = np.zeros((int(3047/3), 2))
midx = np.zeros((int(233355/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(3047/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(233355/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(1015, 2)
(7778, 2)
[[4.95210e+04 4.27700e+00]
 [4.95200e+04 4.26900e+00]
 [4.95280e+04 4.26100e+00]
 ...
 [5.19630e+04 2.52300e+00]
 [1.07396e+05 2.52200e+00]
 [2.28366e+05 2.52200e+00]]
[[2.28019e+05 2.52100e+00]
 [2.13668e+05 2.51700e+00]
 [2.28021e+05 2.51400e+00]
 ...
 [6.90020e+04 1.55000e-02]
 [1.86238e+05 1.55000e-02]
 [2.20414e+05 1.55000e-02]]


In [37]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch6训练.csv',index=False)

(8793, 2)


In [38]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch7.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.753:
        num = num+1
print(num)

(983305, 2)
18895


In [39]:
high = data[0:18895][:]
print(high.shape)
mid = data[18895:983305][:]
print(mid.shape)

(18895, 2)
(964410, 2)


In [40]:
highx = np.zeros((int(18895/3), 2))
midx = np.zeros((int(964410/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(18895/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(964410/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(6298, 2)
(32147, 2)
[[1.026191e+06 6.125000e+00]
 [1.026210e+06 6.097000e+00]
 [1.026216e+06 6.090000e+00]
 ...
 [6.473580e+05 2.753000e+00]
 [9.825770e+05 2.753000e+00]
 [9.682120e+05 2.753000e+00]]
[[4.120020e+05 2.752000e+00]
 [9.362810e+05 2.752000e+00]
 [1.043355e+06 2.751000e+00]
 ...
 [6.077000e+03 1.550000e-02]
 [8.996500e+04 1.550000e-02]
 [8.994800e+04 1.550000e-02]]


In [41]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch7训练.csv',index=False)

(38445, 2)


In [42]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch8.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.574:
        num = num+1
print(num)

(484641, 2)
9618


In [43]:
high = data[0:9618][:]
print(high.shape)
mid = data[9618:484641][:]
print(mid.shape)

(9618, 2)
(475023, 2)


In [44]:
highx = np.zeros((int(9618/3), 2))
midx = np.zeros((int(475023/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(9618/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(475023/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(3206, 2)
(15834, 2)
[[5.55890e+04 4.41400e+00]
 [5.55830e+04 4.40700e+00]
 [5.55790e+04 4.40600e+00]
 ...
 [3.25346e+05 2.57400e+00]
 [5.50800e+04 2.57400e+00]
 [3.41088e+05 2.57400e+00]]
[[2.32717e+05 2.57300e+00]
 [1.88922e+05 2.57200e+00]
 [3.28510e+05 2.56900e+00]
 ...
 [2.21377e+05 1.55000e-02]
 [1.08303e+05 1.55000e-02]
 [2.82612e+05 1.52000e-02]]


In [45]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch8训练.csv',index=False)

(19040, 2)


In [46]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch9.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.6:
        num = num+1
print(num)

(382415, 2)
5081


In [47]:
high = data[0:5081][:]
print(high.shape)
mid = data[5081:382415][:]
print(mid.shape)

(5081, 2)
(377334, 2)


In [48]:
highx = np.zeros((int(5081/3), 2))
midx = np.zeros((int(377334/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(5081/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(377334/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(1693, 2)
(12577, 2)
[[1.06648e+05 3.64600e+00]
 [1.99986e+05 3.62600e+00]
 [1.99974e+05 3.62600e+00]
 ...
 [4.31273e+05 2.60000e+00]
 [4.31274e+05 2.60000e+00]
 [4.31278e+05 2.60000e+00]]
[[1.49501e+05 2.59900e+00]
 [2.53193e+05 2.59800e+00]
 [5.23850e+04 2.59700e+00]
 ...
 [1.05786e+05 1.55000e-02]
 [2.46001e+05 1.55000e-02]
 [2.45968e+05 1.55000e-02]]


In [49]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch9训练.csv',index=False)

(14270, 2)


In [50]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch10.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.712:
        num = num+1
print(num)

(659529, 2)
12292


In [51]:
high = data[0:12292][:]
print(high.shape)
mid = data[12292:659529][:]
print(mid.shape)

(12292, 2)
(647237, 2)


In [52]:
highx = np.zeros((int(12292/3), 2))
midx = np.zeros((int(647237/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(12292/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(647237/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(4097, 2)
(21574, 2)
[[3.56328e+05 4.62500e+00]
 [3.56327e+05 4.59500e+00]
 [3.56286e+05 4.59200e+00]
 ...
 [6.47657e+05 2.71200e+00]
 [3.37901e+05 2.71200e+00]
 [3.82550e+05 2.71200e+00]]
[[3.59831e+05 2.71100e+00]
 [6.23744e+05 2.71100e+00]
 [5.57249e+05 2.71000e+00]
 ...
 [3.47283e+05 1.55000e-02]
 [9.95630e+04 1.55000e-02]
 [4.36299e+05 1.55000e-02]]


In [53]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch10训练.csv',index=False)

(25671, 2)


In [54]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch11.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.623:
        num = num+1
print(num)

(632626, 2)
13357


In [55]:
high = data[0:13357][:]
print(high.shape)
mid = data[13357:632626][:]
print(mid.shape)

(13357, 2)
(619269, 2)


In [56]:
highx = np.zeros((int(13357/3), 2))
midx = np.zeros((int(619269/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(13357/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(619269/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(4452, 2)
(20642, 2)
[[5.19608e+05 4.88200e+00]
 [5.19603e+05 4.88200e+00]
 [5.19606e+05 4.88200e+00]
 ...
 [4.99952e+05 2.62300e+00]
 [3.26811e+05 2.62300e+00]
 [1.78570e+04 2.62300e+00]]
[[5.08801e+05 2.62200e+00]
 [2.07170e+04 2.62100e+00]
 [3.69607e+05 2.61900e+00]
 ...
 [3.25935e+05 1.55000e-02]
 [4.39817e+05 1.55000e-02]
 [4.39857e+05 1.55000e-02]]


In [57]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch11训练.csv',index=False)

(25094, 2)


In [58]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch12.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.93:
        num = num+1
print(num)

(931931, 2)
17721


In [59]:
high = data[0:17721][:]
print(high.shape)
mid = data[17721:931931][:]
print(mid.shape)

(17721, 2)
(914210, 2)


In [60]:
highx = np.zeros((int(17721/3), 2))
midx = np.zeros((int(914210/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(17721/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(914210/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(5907, 2)
(30473, 2)
[[2.51692e+05 5.02900e+00]
 [2.51694e+05 5.02100e+00]
 [2.51671e+05 5.01400e+00]
 ...
 [8.84443e+05 2.93000e+00]
 [9.49838e+05 2.93000e+00]
 [2.54817e+05 2.93000e+00]]
[[7.15795e+05 2.92900e+00]
 [3.89519e+05 2.92800e+00]
 [1.69521e+05 2.92800e+00]
 ...
 [6.99944e+05 1.55000e-02]
 [5.07612e+05 1.52000e-02]
 [4.12470e+04 1.52000e-02]]


In [61]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch12训练.csv',index=False)

(36380, 2)


In [62]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch13.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.703:
        num = num+1
print(num)

(848262, 2)
17707


In [63]:
high = data[0:17707][:]
print(high.shape)
mid = data[17707:848262][:]
print(mid.shape)

(17707, 2)
(830555, 2)


In [64]:
highx = np.zeros((int(17707/3), 2))
midx = np.zeros((int(830555/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(17707/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(830555/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(5902, 2)
(27685, 2)
[[1.61213e+05 4.66800e+00]
 [1.61237e+05 4.66000e+00]
 [1.61212e+05 4.66000e+00]
 ...
 [2.40744e+05 2.70300e+00]
 [7.10852e+05 2.70300e+00]
 [6.57949e+05 2.70300e+00]]
[[4.6509e+05 2.7020e+00]
 [1.9971e+04 2.7020e+00]
 [4.5489e+04 2.7010e+00]
 ...
 [8.7036e+04 1.5200e-02]
 [8.6980e+04 1.5200e-02]
 [8.6976e+04 1.5200e-02]]


In [65]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch13训练.csv',index=False)

(33587, 2)


In [66]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch14.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.715:
        num = num+1
print(num)

(706446, 2)
14017


In [67]:
high = data[0:14017][:]
print(high.shape)
mid = data[14017:706446][:]
print(mid.shape)

(14017, 2)
(692429, 2)


In [68]:
highx = np.zeros((int(14017/3), 2))
midx = np.zeros((int(692429/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(14017/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(692429/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(4672, 2)
(23080, 2)
[[5.58244e+05 5.19000e+00]
 [5.58249e+05 5.15800e+00]
 [5.58236e+05 5.15100e+00]
 ...
 [5.87640e+04 2.71500e+00]
 [6.03014e+05 2.71500e+00]
 [7.41254e+05 2.71500e+00]]
[[5.26312e+05 2.71400e+00]
 [2.25622e+05 2.71400e+00]
 [6.20216e+05 2.71300e+00]
 ...
 [2.35829e+05 1.55000e-02]
 [2.83546e+05 1.55000e-02]
 [2.83520e+05 1.55000e-02]]


In [69]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch14训练.csv',index=False)

(27752, 2)


In [70]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch15.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.709:
        num = num+1
print(num)

(997401, 2)
17860


In [71]:
high = data[0:17860][:]
print(high.shape)
mid = data[17860:997401][:]
print(mid.shape)

(17860, 2)
(979541, 2)


In [72]:
highx = np.zeros((int(17860/3), 2))
midx = np.zeros((int(979541/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(17860/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(979541/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(5953, 2)
(32651, 2)
[[1.62894e+05 4.59800e+00]
 [1.62892e+05 4.59000e+00]
 [1.62897e+05 4.59000e+00]
 ...
 [5.58970e+04 2.70900e+00]
 [3.16751e+05 2.70900e+00]
 [2.04955e+05 2.70900e+00]]
[[3.185690e+05 2.708000e+00]
 [1.064183e+06 2.707000e+00]
 [4.448360e+05 2.707000e+00]
 ...
 [4.570600e+04 1.550000e-02]
 [1.451820e+05 1.550000e-02]
 [1.074128e+06 1.520000e-02]]


In [73]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch15训练.csv',index=False)

(38604, 2)


In [74]:
import numpy as np
import csv
import pandas as pd
path_csv = "分类染色体/ch16.csv"  
data = np.loadtxt(open(path_csv,"rb"),delimiter=",",skiprows=1,usecols=[2,3]) 
print(data.shape)
num = 0
for i in range(len(data)):
    if data[i][1] >= 2.62:
        num = num+1
print(num)

(856960, 2)
20013


In [75]:
high = data[0:20013][:]
print(high.shape)
mid = data[20013:856960][:]
print(mid.shape)

(20013, 2)
(836947, 2)


In [76]:
highx = np.zeros((int(20013/3), 2))
midx = np.zeros((int(836947/30), 2))
print(highx.shape)
print(midx.shape)
for h in range(int(20013/3)):
    ht = h*3
    highx[h][0] = high[ht][0]
    highx[h][1] = high[ht][1]
print(highx)
for m in range(int(836947/30)):
    mt = m*30
    midx[m][0] = mid[mt][0]
    midx[m][1] = mid[mt][1]
print(midx)

(6671, 2)
(27898, 2)
[[5.74588e+05 5.68100e+00]
 [5.74593e+05 5.68100e+00]
 [5.74590e+05 5.68100e+00]
 ...
 [2.63022e+05 2.62000e+00]
 [4.61313e+05 2.62000e+00]
 [7.34301e+05 2.62000e+00]]
[[4.22523e+05 2.61900e+00]
 [8.61912e+05 2.61900e+00]
 [1.10726e+05 2.61800e+00]
 ...
 [6.81024e+05 1.55000e-02]
 [9.39159e+05 1.55000e-02]
 [6.81090e+05 1.55000e-02]]


In [77]:
Nuar = np.concatenate([highx, midx])
print(Nuar.shape)
site = Nuar[:,0]
level = Nuar[:,1]
df = pd.DataFrame(Nuar,columns=['site','value'])
df.to_csv('训练位点和占据率/ch16训练.csv',index=False)

(34569, 2)


训练位点数:    6557    29077    9140    54068    19920    8793    38445    19040    14270    25671    25094    36380    33587    27752    38604    34569

In [78]:
import numpy as np
import pandas as pd
import h5py

In [80]:
f1 = np.loadtxt('训练位点和占据率/ch1训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f1.shape)
f2 = np.loadtxt('训练位点和占据率/ch2训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f2.shape)
f3 = np.loadtxt('训练位点和占据率/ch3训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f3.shape)
f4 = np.loadtxt('训练位点和占据率/ch4训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f4.shape)
f5 = np.loadtxt('训练位点和占据率/ch5训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f5.shape)
f6 = np.loadtxt('训练位点和占据率/ch6训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f6.shape)
f7 = np.loadtxt('训练位点和占据率/ch7训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f7.shape)
f8 = np.loadtxt('训练位点和占据率/ch8训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f8.shape)
f9 = np.loadtxt('训练位点和占据率/ch9训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f9.shape)
f10 = np.loadtxt('训练位点和占据率/ch10训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f10.shape)
f11 = np.loadtxt('训练位点和占据率/ch11训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f11.shape)
f12 = np.loadtxt('训练位点和占据率/ch12训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f12.shape)
f13 = np.loadtxt('训练位点和占据率/ch13训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f13.shape)
f14 = np.loadtxt('训练位点和占据率/ch14训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f14.shape)
f15 = np.loadtxt('训练位点和占据率/ch15训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f15.shape)
f16 = np.loadtxt('训练位点和占据率/ch16训练.csv',delimiter=",", skiprows=1, usecols=[1]) 
print(f16.shape)
level = np.hstack((f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16)) 
print(level.shape)
level_no10 = np.hstack((f1,f2,f3,f4,f5,f6,f7,f8,f9,f11,f12,f13,f14,f15,f16)) 
print(level_no10.shape)
f = h5py.File('训练位点和占据率/训练标签A.h5', 'w')
f.create_dataset('level', data=level)
f.close()
f = h5py.File('训练位点和占据率/训练标签A(no10).h5', 'w')
f.create_dataset('level', data=level_no10)
f.close()

(6557,)
(29077,)
(9140,)
(54086,)
(19920,)
(8793,)
(38445,)
(19040,)
(14270,)
(25671,)
(25094,)
(36380,)
(33587,)
(27752,)
(38604,)
(34569,)
(420985,)
(395314,)
